### ISSUE TITLE
Neither python2 nor python3 work

### ISSUE THREAD

**Issue by martin-braun** [Kevaljagani/Google-Maps-API-Scanner#1]
```sh
$% python3 ./Scanner.py 
  File "/opt/github/Kevaljagani/Google-Maps-API-Scanner/./Scanner.py", line 11
    print "API key is \033[1;31;40m vulnerable \033[0m for Staticmap API! BOOM! Here is the Link "
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("API key is \033[1)?
$% python2 ./Scanner.py
Traceback (most recent call last):
  File "./Scanner.py", line 1, in <module>
    import requests
ImportError: No module named requests
```

**Comment by EsamLasheen** [comment]
**how were you solve this problem?**

**Comment by r4d1k4l** [comment]
Hey @martin-braun @EsamLasheen  you need to install requests module with `pip install requests`
I created a PR with fixes, until it is merged by @Kevaljagani the working for is here: https://github.com/r4d1k4l/Google-Maps-API-Scanner
Update: PR has been auto-merged, so if you `git pull` it should work now :smiley:
